#!/bin/sh
#
# Debrid your link using Alldebrid
#
# Author: Hedi Nasr - h.nsr69@gmail.com

ALLDEBRID_ROOT="https://alldebrid.com"
ALLDEBRID_LOGIN="register/?action=login&returnpage=%2Faccount%2F"

### Connect to your Alldebrid account
### -> connect <login> <password>
connect() {
    LOCATION="$(curl --silent -I "$ALLDEBRID_ROOT/$ALLDEBRID_LOGIN&login_login=$1&login_password=$2" \
    		     -c /tmp/cookie-jar | perl -n -e '/^Location: (.*)\r$/ && print "$1\n"')"
    if [ "$LOCATION" != "https://alldebrid.com/account/" ]
    then
        echo 'Login failed'
	exit 1
    fi
}

### Debrid your url with Alldebrid
### -> debrid <url>
debrid() {
    DEBRID="$(curl --silent -b cookie-jar "$ALLDEBRID_ROOT/service.php?link=$1&json=true")"
    if (! echo "$DEBRID" | grep '"error":""') > /dev/null
    then
        # check error message
        error=`echo "$DEBRID" | python -c "import sys, json; print(json.load(sys.stdin)['error'])"`
        if [ $error = "premium" ]
        then
            echo "You're account is not a premium account!"
	    exit 1
        else
            echo "Bad link"
	    exit 1
        fi
    else
        #echo "$DEBRID" | sed -e 's/^.*"link"[ ]*:[ ]*"//' -e 's/".*//' | sed 's/\\//g'
        echo "$DEBRID" | python -c "import sys, json; print(json.load(sys.stdin)['link'])"
    fi
}

### Usage info
print_help() {
    cat <<EOF
Usage: ${0##*/} [-hv] <URL>

       -h	display this help and exit.
       -v	verbose mode.
EOF
}

while getopts ":hv" opt; do
    case $opt in
	h) ## Help
	    print_help
	    exit 0
	    ;;
	v) ## Verbose
	    verbose=1
	    ;;
	\?)
	    echo "Invalid option: -$OPTARG" >&2
	    print_help
	    exit 1
	    ;;
    esac
done

shift "$((OPTIND - 1))"

if [ "$#" -ne 1 ]
then
    print_help
    exit 1
else
if [ -e "/tmp/cookie-jar" ]
    then
        debrid "$1"
	exit 0
    else
        echo "Login: " && read login
        echo "Password: " && read -s password
        connect "$login" "$password"
        debrid "$1"
	exit 0
    fi
fi
